from typing import Any, Sequence
import numpy as np
import pandas as pd

def to_numeric(
    arg: pd.Series | list[Any] | tuple[Any] | np.ndarray[Any],
    errors: str = ...,
    downcast: str | None = ...,
) -> pd.Series: ...

class Series:
    def dropna(self, inplace: bool = ...) -> "Series": ...
    def fillna(self, value: Any, inplace: bool = ...) -> "Series": ...
    def min(self) -> Any: ...
    def max(self) -> Any: ...

class DataFrame:
    def dropna(
        self,
        axis: int | str = ...,
        how: str = ...,
        thresh: int = ...,
        subset: Sequence[str] | None = ...,
        inplace: bool = ...,
    ) -> "DataFrame": ...
    def fillna(self, value: Any, inplace: bool = ...) -> "DataFrame": ...
    def min(self) -> Series: ...
    def max(self) -> Series: ...
