from typing import Any

class Axes:
    def set_title(self, label: str, **kwargs: Any) -> None: ...
    def set_xlabel(self, xlabel: str, **kwargs: Any) -> None: ...
    def set_ylabel(self, ylabel: str, **kwargs: Any) -> None: ...
